name: Update Public Keys
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "extract"
  cancel-in-progress: true

jobs:
  extract:
    name: Extract Cloudflare Public Keys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Cache
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       node_modules
      #       public-keys/node_modules
      #     key: ${{ runner.os }}-cache-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - run: npm --prefix public-keys install
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      - name: Extract PublicKey
        uses: mujo-code/puppeteer-headful@master
        with:
          args: npm --prefix public-keys run extract
      - name: Commit to branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Public Keys"
